FROM nvidia/cuda:12.6.3-runtime-ubuntu22.04

# Set non-interactive environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/London \
    LANG=en_GB.UTF-8 \
    LANGUAGE=en_GB:en \
    LC_ALL=en_GB.UTF-8

WORKDIR /home/workspace

# python
RUN apt-get update && \
    apt-get install -y software-properties-common apt-utils && \
    add-apt-repository ppa:apt-fast/stable -y && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && \
    apt-get install -y apt-fast apt-transport-https && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-fast install -y --no-install-recommends \
           locales \
           tzdata \
           mesa-utils \
           libgl1-mesa-dri \
           libgtkgl2.0-dev \
           libgtkglext1-dev \
           git \
           curl \
           pkg-config \
           python3.12 \
           python3.12-dev \
           python3.12-venv \
           python3-pip

RUN echo "en_GB.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=en_GB.UTF-8 && \
    ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && \
    echo "Europe/London" > /etc/timezone && \
    rm -rf /var/lib/apt/lists/*

# Set the default Python version to 3
RUN ln -s /usr/bin/python3.12 /usr/bin/python

# Set environment variables for virtual environment
ENV VENV_DIR=/root/.venv
ENV PATH="$VENV_DIR/bin:$PATH"

# Create and activate the virtual environment, then install packages
RUN python3.12 -m venv $VENV_DIR && \
    source $VENV_DIR/bin/activate && \
    pip install --upgrade pip
RUN source $VENV_DIR/bin/activate && \
    pip install --upgrade setuptools

# torch and xformers
RUN source $VENV_DIR/bin/activate && \
    pip install torch==2.6.0 torchvision~=0.21.0 torchaudio~=2.6.0 --extra-index-url https://download.pytorch.org/whl/cu126

ARG COMFYUI_VERSION
ARG COMFYUI_MANAGER_VERSION

# clone ComfyUI
RUN git clone https://github.com/comfyanonymous/ComfyUI.git \
    && cd ComfyUI \
    && git checkout ${COMFYUI_VERSION}
RUN cd ComfyUI/custom_nodes \
    && git clone https://github.com/ltdrdata/ComfyUI-Manager.git \
    && cd ComfyUI-Manager \
    && git checkout ${COMFYUI_MANAGER_VERSION}

# install dependencies
RUN source $VENV_DIR/bin/activate && \
    pip install -r ComfyUI/requirements.txt

# RUN
ENV PYTHON=python3.12
ENV COMFYUI_PATH=/home/workspace/ComfyUI
ENV PATH="$PATH:$COMFYUI_PATH"
WORKDIR $COMFYUI_PATH
CMD ["/bin/bash", "-c", "source", "$VENV_DIR/bin/activate", "&&", "$PYTHON", "main.py", "--listen", "0.0.0.0", "--port", "50000"]
