ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-fast install --yes --no-install-recommends \
        ca-certificates \
        dnsutils \
        iputils-ping \
        tini \
        git \
 && rm -rf /var/lib/apt/lists/*

# Install python packages into the virtual environment
COPY requirements-jupyter.txt requirements.txt
RUN $VENV_DIR/bin/pip install \
      --no-cache-dir \
      --upgrade \
      --force-reinstall \
      -r requirements.txt \
    && rm requirements.txt

# Install jupyter extensions into the virtual environment
COPY extensions /home/extensions
RUN $VENV_DIR/bin/pip install --no-cache-dir /home/extensions/jupyter_comfyui_proxy/. \
    && rm -rf /home/extensions

WORKDIR /home/user
EXPOSE 8888

ENTRYPOINT ["tini","--"]
CMD ["jupyter","lab","--ip","0.0.0.0","--port","8888","--allow-root"]
